### ISSUE TITLE
Add cases for repos that has main branch named "master" in upstream for git sync

### ISSUE THREAD

**Issue by inesqyx** [Cali0707/git-utils#11]
Currently, the script only works for users who interact with upstreams whose main branches are also named "main". However, if the main branches in their upstreams happen to be something else (i.e. master), the script will no longer work. Considering, there are a wide range of repos that named their main branches as "master"., there is a strong call for include this case in the automated script.

**Comment by Cali0707** [comment]
Thanks for reporting this @inesqyx !!
